"""Initial migration

Revision ID: 5fe7acfc54ac
Revises: 
Create Date: 2025-07-27 19:32:28.596910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe7acfc54ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('tunnel_key', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('server_enc_private', sa.Text(), nullable=False))
    op.add_column('sessions', sa.Column('server_enc_public', sa.Text(), nullable=False))
    op.add_column('sessions', sa.Column('server_sign_private', sa.Text(), nullable=False))
    op.add_column('sessions', sa.Column('server_sign_public', sa.Text(), nullable=False))
    op.drop_column('sessions', 'MySigkey')
    op.drop_column('sessions', 'HerSigkey')
    op.drop_column('sessions', 'MyEncKey')
    op.drop_column('sessions', 'HerEncKey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('HerEncKey', sa.TEXT(), nullable=True))
    op.add_column('sessions', sa.Column('MyEncKey', sa.TEXT(), nullable=True))
    op.add_column('sessions', sa.Column('HerSigkey', sa.TEXT(), nullable=True))
    op.add_column('sessions', sa.Column('MySigkey', sa.TEXT(), nullable=True))
    op.drop_column('sessions', 'server_sign_public')
    op.drop_column('sessions', 'server_sign_private')
    op.drop_column('sessions', 'server_enc_public')
    op.drop_column('sessions', 'server_enc_private')
    op.drop_column('sessions', 'tunnel_key')
    # ### end Alembic commands ###
