"""vidk

Revision ID: 715006b59721
Revises: 99d715f12ad6
Create Date: 2025-08-11 15:57:54.221922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715006b59721'
down_revision: Union[str, Sequence[str], None] = '99d715f12ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cards', 'accounts', ['account_id'], ['id'])
    op.add_column('transactions', sa.Column('completed_via', sa.String(), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text('(NULL)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.drop_column('transactions', 'completed_via')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    # ### end Alembic commands ###
