"""Add balance column to accounts

Revision ID: 99d715f12ad6
Revises: 5fe7acfc54ac
Create Date: 2025-08-11 15:20:04.478503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d715f12ad6'
down_revision: Union[str, Sequence[str], None] = '5fe7acfc54ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('account_id', sa.Integer(), nullable=False))
    op.add_column('cards', sa.Column('status', sa.String(), nullable=False))
    op.create_foreign_key(None, 'cards', 'accounts', ['account_id'], ['id'])
    op.add_column('transactions', sa.Column('merchant_account_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_card_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_account_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'accounts', ['merchant_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['receiver_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'cards', ['receiver_card_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['receiver_id'], ['id'])
    op.drop_column('transactions', 'consumer_card_id')
    op.drop_column('transactions', 'consumer_id')
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.add_column('transactions', sa.Column('consumer_id', sa.INTEGER(), nullable=True))
    op.add_column('transactions', sa.Column('consumer_card_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'cards', ['consumer_card_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['consumer_id'], ['id'])
    op.drop_column('transactions', 'receiver_account_id')
    op.drop_column('transactions', 'receiver_card_id')
    op.drop_column('transactions', 'receiver_id')
    op.drop_column('transactions', 'merchant_account_id')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'status')
    op.drop_column('cards', 'account_id')
    # ### end Alembic commands ###
